name: Build Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pygame

    - name: Create Windows build
      run: |
        pyinstaller --onefile --windowed --icon "./player.ico" --name "PlaneWar-windows" --add-data "./sound;sound/" --add-data "img/;img/" --add-data "font.ttf;." --add-data "player.ico;." "planeWar.py"

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: PlaneWar-windows
        path: dist/PlaneWar-windows.exe

    - name: Upload windows spec artifact
      uses: actions/upload-artifact@v4
      with:
        name: PlaneWar-spec-windows
        path: PlaneWar-windows.spec

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pygame

      - name: Create linux build
        run: |
          pyinstaller --onefile --windowed --icon "player.ico" --name "PlaneWar-linux" --add-data=sound:sound/ --add-data=img/:img/ --add-data=font.ttf:. --add-data=player.ico:. "planeWar.py"

      - name: Upload linux build artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlaneWar-linux
          path: dist/PlaneWar-linux

      - name: Upload linux spec artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlaneWar-spec-linux
          path: PlaneWar-linux.spec

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pygame Pillow

    - name: Create macOS build
      run: |
        pyinstaller --onefile --windowed --icon "player.ico" --name "PlaneWar-macos" --add-data=sound:sound/ --add-data=img/:img/ --add-data=font.ttf:. --add-data=player.ico:. "planeWar.py"
  
    - name: Upload macos build artifact
      uses: actions/upload-artifact@v4
      with:
        name: PlaneWar-macos
        path: dist/PlaneWar-macos
    
    - name: Upload macos spec artifact
      uses: actions/upload-artifact@v4
      with:
        name: PlaneWar-spec-macos
        path: PlaneWar-macos.spec